### 1. 사용자 생성 (게시글 작성을 위해)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "게시글작성자",
  "email": "author@test.com",
  "age": 25
}

### 2. 첫 번째 게시글 생성
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "첫 번째 게시글",
  "content": "이것은 첫 번째 게시글의 내용입니다.",
  "userId": 1
}

### 3. 두 번째 게시글 생성
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "두 번째 게시글",
  "content": "이것은 두 번째 게시글의 내용입니다.",
  "userId": 1
}

### 4. 모든 게시글 조회 (작성자 정보 포함)
GET http://localhost:3000/posts

### 5. 특정 게시글 조회
GET http://localhost:3000/posts/1

### 6. 특정 사용자의 게시글만 조회
GET http://localhost:3000/posts?userId=1

### 7. 게시글 수정
PUT http://localhost:3000/posts/1
Content-Type: application/json

{
  "title": "수정된 제목"
}

### 8. 게시글 삭제
DELETE http://localhost:3000/posts/2

### 9. 존재하지 않는 사용자로 게시글 생성 시도 (에러)
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "에러 테스트",
  "content": "존재하지 않는 사용자",
  "userId": 999
}

### 10. 빈 객체로 게시글 수정 시도 (에러)
PUT http://localhost:3000/posts/1
Content-Type: application/json

{}

### 11. 사용자와 해당 사용자의 모든 게시글 조회 (User에서)
GET http://localhost:3000/users/1